export const routes = [
  {
    id: "route1",
    vehicleId: "V-101",
    origin: "Siliguri",
    destination: "Gangtok",
    recommended: {
      id: "r1-rec",
      roadName: "NH-10",
      distanceKm: 114,
      etaMinutes: 210,
      riskLevel: "high",
      riskScore: 78,
      delayMinutes: 42,
      reason: "Continuous rainfall over the past 48 hours has raised landslide probability sharply along this stretch.",
      coordinates: [
        [26.727, 88.393],
        [26.966, 88.476],
        [27.331, 88.612],
      ],
    },
    alternative: {
      id: "r1-alt1",
      roadName: "Route via Kalimpong (SH-12)",
      distanceKm: 128,
      etaMinutes: 195,
      riskLevel: "low",
      riskScore: 15,
      delayMinutes: 18,
      reason: "Bypasses the landslide-affected NH-10 stretch entirely and avoids the current rainfall zone.",
      coordinates: [
        [26.727, 88.393],
        [26.900, 88.470],
        [27.057, 88.470],
        [27.331, 88.612],
      ],
    },
    alternative2: {
      id: "r1-alt2",
      roadName: "Route via Teesta Valley (SH-8)",
      distanceKm: 142,
      etaMinutes: 225,
      riskLevel: "medium",
      riskScore: 45,
      delayMinutes: 25,
      reason: "Longer route, but avoids river-adjacent stretches vulnerable to flash flooding.",
      coordinates: [
        [26.727, 88.393],
        [26.850, 88.550],
        [27.100, 88.600],
        [27.331, 88.612],
      ],
    },
  },
  {
    id: "route2",
    vehicleId: "V-103",
    origin: "Imphal",
    destination: "Dimapur",
    recommended: {
      id: "r2-rec",
      roadName: "NH-702",
      distanceKm: 215,
      etaMinutes: 360,
      riskLevel: "critical",
      riskScore: 97,
      delayMinutes: 999,
      reason: "Complete blockade reported due to civil unrest — road is currently inaccessible.",
      coordinates: [
        [24.817, 93.936],
        [25.350, 93.830],
        [25.912, 93.727],
      ],
    },
    alternative: {
      id: "r2-alt1",
      roadName: "Route via Kohima (NH-2 + NH-29)",
      distanceKm: 268,
      etaMinutes: 420,
      riskLevel: "medium",
      riskScore: 55,
      delayMinutes: 65,
      reason: "Only viable route with the direct NH-702 corridor fully blocked; moderate congestion expected from rerouted traffic.",
      coordinates: [
        [24.817, 93.936],
        [25.671, 94.108],
        [25.912, 93.727],
      ],
    },
    alternative2: {
      id: "r2-alt2",
      roadName: "Route via Ukhrul (SH-1)",
      distanceKm: 302,
      etaMinutes: 480,
      riskLevel: "medium",
      riskScore: 40,
      delayMinutes: 90,
      reason: "Longer mountain route, but currently clear of blockades and has lower congestion.",
      coordinates: [
        [24.817, 93.936],
        [25.100, 94.350],
        [25.912, 93.727],
      ],
    },
  },
  {
    id: "route3",
    vehicleId: "V-102",
    origin: "Guwahati",
    destination: "Shillong",
    recommended: {
      id: "r3-rec",
      roadName: "NH-2",
      distanceKm: 100,
      etaMinutes: 150,
      riskLevel: "low",
      riskScore: 10,
      delayMinutes: 5,
      reason: "Clear road conditions with no active risk factors currently detected.",
      coordinates: [
        [26.144, 91.736],
        [25.578, 91.893],
      ],
    },
    alternative: {
      id: "r3-alt1",
      roadName: "Route via Nongpoh (SH-5)",
      distanceKm: 112,
      etaMinutes: 165,
      riskLevel: "low",
      riskScore: 18,
      delayMinutes: 10,
      reason: "Slightly longer, kept as backup in case of NH-2 congestion.",
      coordinates: [
        [26.144, 91.736],
        [25.899, 91.878],
        [25.578, 91.893],
      ],
    },
    alternative2: {
      id: "r3-alt2",
      roadName: "Route via Ri-Bhoi (SH-9)",
      distanceKm: 118,
      etaMinutes: 175,
      riskLevel: "medium",
      riskScore: 35,
      delayMinutes: 15,
      reason: "Scenic alternate route; occasional early-morning fog reduces visibility.",
      coordinates: [
        [26.144, 91.736],
        [25.950, 91.950],
        [25.578, 91.893],
      ],
    },
  },
];